name: cron_parser
description: A cron parser. Spits out next cron dates starting from now or a specific date.
version: 0.6.0
repository: https://github.com/rbubke/cron-parser
homepage: https://github.com/rbubke/cron-parser

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  timezone: ^0.8.0

dev_dependencies:
  test: ^1.14.2